"""
Parity and regression tests for metrics extraction (Phase 4).

These tests verify that the metrics.py implementation produces
bit-exact identical values to the metrics attached to StrategyResult
instances generated by the backtest engine.
"""
from dataclasses import asdict
from pathlib import Path
import math
import json
import sys

import pandas as pd
import pytest

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from core.backtest_engine import (  # noqa: E402
    StrategyResult,
    TradeRecord,
    load_data,
    prepare_dataset_with_warmup,
)
from core.metrics import (  # noqa: E402
    calculate_basic,
    calculate_advanced,
    _calculate_r2_consistency,
    _calculate_sqn_value,
)
from strategies.s01_trailing_ma.strategy import S01Params, S01TrailingMA  # noqa: E402

PROJECT_ROOT = Path(__file__).parent.parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "OKX_LINKUSDT.P, 15 2025.05.01-2025.11.20.csv"
BASELINE_PATH = PROJECT_ROOT / "data" / "baseline" / "s01_metrics.json"


@pytest.fixture(scope="module")
def test_data():
    df = load_data(str(DATA_PATH))
    return df


@pytest.fixture(scope="module")
def baseline_params():
    with open(BASELINE_PATH, "r") as f:
        baseline = json.load(f)
    return baseline["parameters"], baseline


@pytest.fixture(scope="module")
def test_result(test_data, baseline_params):
    params_dict, baseline = baseline_params
    params = S01Params.from_dict(params_dict)

    start_ts = pd.Timestamp(params_dict["start"], tz="UTC")
    end_ts = pd.Timestamp(params_dict["end"], tz="UTC")
    warmup_bars = baseline["warmup_bars"]

    df_prepared, trade_start_idx = prepare_dataset_with_warmup(
        test_data, start_ts, end_ts, warmup_bars
    )

    result = S01TrailingMA.run(df_prepared, asdict(params), trade_start_idx)
    return result


class TestMetricsParity:
    """Test parity between StrategyResult values and metrics module."""

    def test_basic_net_profit_matches(self, test_result):
        basic = calculate_basic(test_result)
        assert basic.net_profit == pytest.approx(test_result.net_profit)
        assert basic.net_profit_pct == pytest.approx(test_result.net_profit_pct)

    def test_basic_drawdown_matches(self, test_result):
        basic = calculate_basic(test_result)
        assert basic.max_drawdown == pytest.approx(test_result.max_drawdown)
        assert basic.max_drawdown_pct == pytest.approx(test_result.max_drawdown_pct)

    def test_basic_trade_counts_match(self, test_result):
        basic = calculate_basic(test_result)
        assert basic.total_trades == test_result.total_trades
        assert basic.winning_trades == test_result.winning_trades
        assert basic.losing_trades == test_result.losing_trades

    def test_advanced_profit_factor_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.profit_factor == pytest.approx(test_result.profit_factor)

    def test_advanced_romad_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.romad == pytest.approx(test_result.romad)

    def test_advanced_ulcer_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.ulcer_index == pytest.approx(test_result.ulcer_index)

    def test_advanced_sqn_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        if test_result.sqn is None:
            assert advanced.sqn is None
        else:
            assert advanced.sqn == pytest.approx(test_result.sqn)

    def test_advanced_consistency_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.consistency_score == pytest.approx(test_result.consistency_score)


class TestMetricsEdgeCases:
    """Test metrics calculation with edge scenarios."""

    def test_zero_trades(self):
        result = StrategyResult(
            trades=[],
            equity_curve=[10000.0],
            balance_curve=[10000.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        basic = calculate_basic(result)
        advanced = calculate_advanced(result)

        assert basic.total_trades == 0
        assert basic.net_profit_pct == 0.0
        assert basic.win_rate == 0.0
        assert basic.avg_win == 0.0
        assert basic.avg_loss == 0.0
        assert advanced.profit_factor is None
        assert advanced.sharpe_ratio is None

    def test_all_winning_trades(self):
        trades = [
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-01", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-02", tz="UTC"),
                entry_price=100.0,
                exit_price=110.0,
                size=1.0,
                net_pnl=10.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-03", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-04", tz="UTC"),
                entry_price=110.0,
                exit_price=120.0,
                size=1.0,
                net_pnl=10.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-05", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-06", tz="UTC"),
                entry_price=120.0,
                exit_price=130.0,
                size=1.0,
                net_pnl=10.0,
            ),
        ]

        result = StrategyResult(
            trades=trades,
            equity_curve=[10000, 10010, 10020, 10030],
            balance_curve=[10000, 10010, 10020, 10030],
            timestamps=[
                pd.Timestamp("2025-01-01", tz="UTC"),
                pd.Timestamp("2025-01-02", tz="UTC"),
                pd.Timestamp("2025-01-04", tz="UTC"),
                pd.Timestamp("2025-01-06", tz="UTC"),
            ],
        )

        basic = calculate_basic(result)
        advanced = calculate_advanced(result)

        assert basic.total_trades == 3
        assert basic.winning_trades == 3
        assert basic.losing_trades == 0
        assert basic.win_rate == 100.0
        assert basic.gross_profit == 30.0
        assert basic.gross_loss == 0.0
        assert math.isinf(advanced.profit_factor)

    def test_all_losing_trades(self):
        trades = [
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-01", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-02", tz="UTC"),
                entry_price=100.0,
                exit_price=90.0,
                size=1.0,
                net_pnl=-10.0,
            ),
        ]

        result = StrategyResult(
            trades=trades,
            equity_curve=[10000, 9990],
            balance_curve=[10000, 9990],
            timestamps=[
                pd.Timestamp("2025-01-01", tz="UTC"),
                pd.Timestamp("2025-01-02", tz="UTC"),
            ],
        )

        basic = calculate_basic(result)
        advanced = calculate_advanced(result)

        assert basic.winning_trades == 0
        assert basic.losing_trades == 1
        assert basic.win_rate == 0.0
        assert advanced.profit_factor == 0.0

    def test_max_consecutive_losses_includes_breakeven(self):
        trades = [
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-01", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-02", tz="UTC"),
                entry_price=100.0,
                exit_price=95.0,
                size=1.0,
                net_pnl=-5.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-03", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-04", tz="UTC"),
                entry_price=95.0,
                exit_price=95.0,
                size=1.0,
                net_pnl=0.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-05", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-06", tz="UTC"),
                entry_price=95.0,
                exit_price=90.0,
                size=1.0,
                net_pnl=-5.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-07", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-08", tz="UTC"),
                entry_price=90.0,
                exit_price=100.0,
                size=1.0,
                net_pnl=10.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-09", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-10", tz="UTC"),
                entry_price=100.0,
                exit_price=98.0,
                size=1.0,
                net_pnl=-2.0,
            ),
        ]

        result = StrategyResult(
            trades=trades,
            equity_curve=[100.0, 95.0, 95.0, 90.0, 100.0, 98.0],
            balance_curve=[100.0, 95.0, 95.0, 90.0, 100.0, 98.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")] * 6,
        )

        basic = calculate_basic(result, initial_balance=100.0)
        assert basic.max_consecutive_losses == 3

    def test_calculate_sqn_sufficient_trades(self):
        trades = [
            TradeRecord(net_pnl=100 + i) for i in range(30)
        ]
        sqn = _calculate_sqn_value(trades)
        assert sqn is not None
        assert isinstance(sqn, float)

    def test_calculate_sqn_insufficient_trades(self):
        trades = [TradeRecord(net_pnl=100) for _ in range(29)]
        sqn = _calculate_sqn_value(trades)
        assert sqn is None

    def test_calculate_sqn_zero_variance(self):
        trades = [TradeRecord(net_pnl=100) for _ in range(30)]
        sqn = _calculate_sqn_value(trades)
        assert sqn is None

    def test_calculate_sqn_negative_expectancy(self):
        trades = [TradeRecord(net_pnl=-(10 + i)) for i in range(30)]
        sqn = _calculate_sqn_value(trades)
        assert sqn is not None
        assert sqn < 0


class TestR2Consistency:
    """Unit tests for the signed R² consistency metric."""

    def test_perfect_compounded_growth_returns_positive_one(self):
        equity = [100.0, 110.0, 121.0, 133.1, 146.41]
        assert _calculate_r2_consistency(equity) == pytest.approx(1.0)

    def test_perfect_compounded_decline_returns_negative_one(self):
        equity = [146.41, 133.1, 121.0, 110.0, 100.0]
        assert _calculate_r2_consistency(equity) == pytest.approx(-1.0)

    def test_same_shape_different_scale_returns_same_score(self):
        eq_small = [100.0, 110.0, 121.0, 133.1, 146.41]
        eq_large = [1000.0, 1100.0, 1210.0, 1331.0, 1464.1]
        assert _calculate_r2_consistency(eq_small) == pytest.approx(
            _calculate_r2_consistency(eq_large),
            abs=1e-12,
        )

    def test_flat_curve_returns_zero(self):
        assert _calculate_r2_consistency([100.0] * 10) == pytest.approx(0.0)

    def test_raw_equity_fallback_handles_non_positive_curves(self):
        equity = [-10.0, -5.0, 0.0, 5.0, 10.0]
        assert _calculate_r2_consistency(equity) == pytest.approx(1.0)

    def test_positive_endpoint_does_not_force_positive_sign(self):
        equity = [100.0, 80.0, 60.0, 40.0, 101.0]
        score = _calculate_r2_consistency(equity)
        assert score is not None
        assert score < 0.0

    def test_invalid_input_returns_none(self):
        assert _calculate_r2_consistency([]) is None
        assert _calculate_r2_consistency([100.0, 110.0]) is None
        assert _calculate_r2_consistency([100.0, float("nan"), 120.0]) is None


class TestMetricsRegression:
    """Regression checks against recorded baseline values."""

    def test_baseline_basic_matches(self, test_result, baseline_params):
        _, baseline = baseline_params
        expected_net_profit_pct = baseline["net_profit_pct"]
        expected_max_dd_pct = baseline["max_drawdown_pct"]
        expected_trades = baseline["total_trades"]

        basic = calculate_basic(test_result)

        assert abs(basic.net_profit_pct - expected_net_profit_pct) < 0.01
        assert abs(basic.max_drawdown_pct - expected_max_dd_pct) < 0.01
        assert basic.total_trades == expected_trades

    def test_baseline_advanced_matches(self, test_result, baseline_params):
        _, baseline = baseline_params
        advanced = calculate_advanced(test_result)

        assert abs((advanced.sharpe_ratio or 0) - baseline["sharpe_ratio"]) < 1e-6
        assert abs((advanced.profit_factor or 0) - baseline["profit_factor"]) < 1e-6
        assert abs((advanced.romad or 0) - baseline["romad"]) < 1e-6
        baseline_sqn = baseline.get("sqn")
        if baseline_sqn is None:
            assert advanced.sqn is None
        else:
            assert abs((advanced.sqn or 0) - baseline_sqn) < 1e-6
        assert abs((advanced.ulcer_index or 0) - baseline["ulcer_index"]) < 1e-6
        assert abs((advanced.consistency_score or 0) - baseline["consistency_score"]) < 1e-6


class TestEnrichStrategyResult:
    """Test the enrich_strategy_result helper and drift guards."""

    def test_enrich_attaches_declared_fields(self):
        """Verify declared StrategyResult fields are populated."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0, 105.0, 110.0],
            balance_curve=[100.0, 105.0, 110.0],
            timestamps=[
                pd.Timestamp("2025-01-01", tz="UTC"),
                pd.Timestamp("2025-01-02", tz="UTC"),
                pd.Timestamp("2025-01-03", tz="UTC"),
            ],
        )

        basic, advanced = enrich_strategy_result(result, initial_balance=100.0)

        # Verify declared fields are attached correctly
        assert result.net_profit == pytest.approx(basic.net_profit)
        assert result.net_profit_pct == pytest.approx(basic.net_profit_pct)
        assert result.max_drawdown_pct == pytest.approx(basic.max_drawdown_pct)
        assert result.total_trades == basic.total_trades

    def test_drift_guard_win_rate_not_attached(self):
        """win_rate exists in BasicMetrics but NOT in StrategyResult."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        enrich_strategy_result(result, initial_balance=100.0)

        # win_rate should NOT be attached (not declared in StrategyResult)
        assert not hasattr(result, "win_rate")

    def test_drift_guard_sortino_not_attached(self):
        """sortino_ratio exists in AdvancedMetrics but NOT in StrategyResult."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        enrich_strategy_result(result, initial_balance=100.0)

        # sortino_ratio should NOT be attached (not declared in StrategyResult)
        assert not hasattr(result, "sortino_ratio")

    def test_drift_guard_avg_metrics_not_attached(self):
        """avg_win, avg_loss, avg_trade exist in BasicMetrics but NOT in StrategyResult."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        enrich_strategy_result(result, initial_balance=100.0)

        assert not hasattr(result, "avg_win")
        assert not hasattr(result, "avg_loss")
        assert not hasattr(result, "avg_trade")

    def test_returns_both_metric_objects(self):
        """Helper returns BasicMetrics and AdvancedMetrics for full access."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        basic, advanced = enrich_strategy_result(result, initial_balance=100.0)

        # Callers can access optimization-only metrics from returned objects
        assert hasattr(basic, "win_rate")
        assert hasattr(basic, "avg_win")
        assert hasattr(advanced, "sortino_ratio")
