"""Synthetic pack builders shared by the Pattern Lab data tests.

Every fixture is generated at runtime under the launcher's external temporary
root.  No market data, binary fixture or real pack is committed or read.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import numpy as np

from tools.pattern_lab import data as pack_data
from tools.pattern_lab import manifest as pack_manifest

REPO_ROOT = Path(__file__).resolve().parents[2]
STEP_MS = pack_manifest.BASE_STEP_MS
# A UTC-day aligned anchor so 5/10/30/60m group boundaries are easy to hand-check.
ANCHOR_MS = 1_760_000_000_000 - (1_760_000_000_000 % 86_400_000)
GENERATED_UTC = "2026-09-14T00:00:00Z"


def utc(epoch_ms: int) -> str:
    """Render epoch milliseconds as the canonical UTC string used in requests."""
    return pack_manifest.format_epoch_ms(int(epoch_ms))


def synthetic_series(
    slot_count: int,
    *,
    anchor_ms: int = ANCHOR_MS,
    first_slot: int = 0,
    drop_slots: Iterable[int] = (),
    dtype: Any = np.float64,
) -> tuple[np.ndarray, np.ndarray]:
    """Build deterministic 5m bars whose values are a function of the UTC slot.

    Values depend only on the absolute slot number, so a pack that also contains
    earlier or later data repeats the same values at the same timestamps, and
    dropping a slot removes one bar without shifting any other bar's values.
    """
    dropped = set(int(item) for item in drop_slots)
    slots = np.array(
        [index for index in range(first_slot, first_slot + slot_count) if index not in dropped],
        dtype=np.int64,
    )
    stamps = anchor_ms + slots * STEP_MS
    position = slots.astype(np.float64)
    open_ = 100.0 + position
    values = np.column_stack(
        [open_, open_ + 2.0, open_ - 1.0, open_ + 1.0, 1000.0 + position]
    ).astype(dtype)
    return stamps, values


def instrument_source(
    timestamps: np.ndarray,
    ohlcv: np.ndarray,
    *,
    symbol: str = "AAA",
    venue: str = "TEST",
    contract: str = "AAA-USDT-SWAP",
    quote_currency: str = "USDT",
    roles: Sequence[str] = ("trading",),
    closed_before_ms: int | None = -1,
    volume_unit_evidence: str = "synthetic quote turnover generated by the test fixture",
    verification: Mapping[str, Any] | None = None,
) -> pack_data.InstrumentSource:
    """Build one publishable instrument; closure defaults to the coverage end.

    ``verification`` replaces the generated block, so a test can publish an
    explicitly malformed or unverified future state.
    """
    if closed_before_ms == -1:
        closed_before_ms = int(timestamps[-1]) + STEP_MS
    closure = None if closed_before_ms is None else utc(closed_before_ms)
    return pack_data.InstrumentSource(
        symbol=symbol,
        venue=venue,
        contract=contract,
        quote_currency=quote_currency,
        roles=list(roles),
        timestamps=timestamps,
        ohlcv=ohlcv,
        source=pack_manifest.build_source_metadata(
            input_format="synthetic",
            input_dtype=str(np.asarray(ohlcv).dtype),
            source_reference="tests/pattern_lab/_helpers.py synthetic generator",
            volume_unit_evidence=volume_unit_evidence,
        ),
        verification=verification
        if verification is not None
        else pack_manifest.build_verification(
            volume_quote_verified=True,
            volume_quote_evidence=volume_unit_evidence,
            closed_before_utc=closure,
            closure_evidence=None if closure is None else "synthetic fixture declares closed bars",
            closure_source=None if closure is None else "tests/pattern_lab/_helpers.py",
        ),
    )


def publish(
    root: Path,
    instruments: Sequence[pack_data.InstrumentSource],
    *,
    universe: Mapping[str, Any] | None = None,
    generated_utc: str = GENERATED_UTC,
    revision: int = 1,
) -> dict[str, Any]:
    """Publish a synthetic pack at ``root``."""
    return pack_data.publish_pack(
        root,
        list(instruments),
        universe=universe or pack_manifest.build_universe(notes="synthetic test fixture"),
        generated_utc=generated_utc,
        revision=revision,
    )


def single_pack(root: Path, *, slot_count: int = 288, **kwargs) -> tuple[np.ndarray, np.ndarray]:
    """Publish a one-instrument pack and return its canonical arrays."""
    stamps, values = synthetic_series(slot_count, drop_slots=kwargs.pop("drop_slots", ()))
    publish(root, [instrument_source(stamps, values, **kwargs)])
    return stamps, values


def read_raw_manifest(root: Path) -> dict[str, Any]:
    """Read the manifest as plain JSON, without Pattern Lab validation."""
    return json.loads((Path(root) / pack_manifest.MANIFEST_NAME).read_text(encoding="utf-8"))


def write_raw_manifest(root: Path, manifest: Mapping[str, Any]) -> None:
    """Write a manifest without validation, for negative and future-state fixtures."""
    (Path(root) / pack_manifest.MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )


def mutate_manifest(root: Path, mutate) -> dict[str, Any]:
    """Apply ``mutate`` to the raw manifest and write it back unvalidated."""
    manifest = read_raw_manifest(root)
    mutate(manifest)
    write_raw_manifest(root, manifest)
    return manifest


# --------------------------------------------------------------------------
# prototype NPZ pack builders, shared by the importer and CLI tests
# --------------------------------------------------------------------------

OKX_ID = "OKX_AAA-USDT-SWAP"
BYBIT_ID = "BYBIT_ENAUSDT"
OKX_ENDPOINT = "GET https://www.okx.com/api/v5/market/history-candles (bar=5m)"


def legacy_series(
    symbol: str = "AAA",
    venue: str = "OKX",
    contract: str = "AAA-USDT-SWAP",
    role: str = "trading",
    slot_count: int = 48,
    **extra: Any,
) -> dict[str, Any]:
    """Describe one prototype series; ``extra`` overrides any generated field."""
    stamps, values = synthetic_series(slot_count)
    spec = {
        "symbol": symbol,
        "venue": venue,
        "contract": contract,
        "role": role,
        "timestamps": stamps,
        "ohlcv": values.astype(np.float32),
        "scalars": True,
        "arrays": None,
    }
    spec.update(extra)
    return spec


def write_legacy_pack(root: Path, specs, *, manifest_overrides=None, entry_overrides=None) -> Path:
    """Write a prototype-layout NPZ pack at ``root`` and return it."""
    root = Path(root)
    (root / "5m").mkdir(parents=True)
    series = []
    for spec in specs:
        path = root / "5m" / f"{spec['symbol']}.npz"
        arrays = spec["arrays"]
        if arrays is None:
            arrays = {"ts": spec["timestamps"], "ohlcv": spec["ohlcv"]}
            if spec["scalars"]:
                arrays["ex"] = np.array(spec.get("scalar_venue", spec["venue"]))
                arrays["sym"] = np.array(spec.get("scalar_symbol", spec["symbol"]))
        np.savez_compressed(path, **arrays)
        entry = {
            "symbol": spec["symbol"],
            "venue": spec["venue"],
            "contract": spec["contract"],
            "role": spec["role"],
            "source_endpoint": OKX_ENDPOINT,
            "base_timeframe": "5m",
            "file": f"5m/{spec['symbol']}.npz",
            "bars": int(np.size(spec["timestamps"])),
            "first_ts_ms": int(np.min(spec["timestamps"])),
            "last_ts_ms": int(np.max(spec["timestamps"])),
            "sha256": pack_manifest.file_sha256(path),
        }
        entry.update(spec.get("entry_overrides") or {})
        entry.update(entry_overrides or {})
        series.append(entry)
    manifest = {
        "manifest_version": 1,
        "generated_utc": "2026-09-13T02:26:59Z",
        "volume_convention": "quote_volume_usd (USD notional), NOT base-asset volume.",
        "gap_policy": "Gaps < 3 bars are forward-filled with a stale flag.",
        "splits": {"discovery": [0.0, 0.65], "validation": [0.65, 0.85], "holdout": [0.85, 1.0],
                   "status": "discovery used; validation and holdout UNTOUCHED as of 2026-09-13"},
        "series": series,
    }
    manifest.update(manifest_overrides or {})
    (root / "MANIFEST.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8", newline="\n")
    return root


def sidecar(instruments=None, **overrides) -> dict[str, Any]:
    """Build a source-metadata sidecar; the default declares only the OKX series."""
    payload = {
        "schema_version": 1,
        "instruments": instruments
        if instruments is not None
        else {
            OKX_ID: {
                "quote_currency": "USDT",
                "volume_unit_evidence": "OKX swap volCcyQuote; fetch_base.py reads candle field 7.",
                "evidence_source": "Source review plus the OKX candle field definition",
            }
        },
    }
    payload.update(overrides)
    return payload
