"""Synthetic pack builders shared by the Pattern Lab data tests.

Every fixture is generated at runtime under the launcher's external temporary
root.  No market data, binary fixture or real pack is committed or read.
"""

from __future__ import annotations

from collections import deque
from datetime import datetime, timedelta, timezone
import json
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence
import urllib.parse

import numpy as np

from tools.pattern_lab import data as pack_data
from tools.pattern_lab import exchange_data
from tools.pattern_lab import manifest as pack_manifest

REPO_ROOT = Path(__file__).resolve().parents[2]
STEP_MS = pack_manifest.BASE_STEP_MS
# A UTC-day aligned anchor so 5/10/30/60m group boundaries are easy to hand-check.
ANCHOR_MS = 1_760_000_000_000 - (1_760_000_000_000 % 86_400_000)
GENERATED_UTC = "2026-09-14T00:00:00Z"


def utc(epoch_ms: int) -> str:
    """Render epoch milliseconds as the canonical UTC string used in requests."""
    return pack_manifest.format_epoch_ms(int(epoch_ms))


def synthetic_series(
    slot_count: int,
    *,
    anchor_ms: int = ANCHOR_MS,
    first_slot: int = 0,
    drop_slots: Iterable[int] = (),
    dtype: Any = np.float64,
) -> tuple[np.ndarray, np.ndarray]:
    """Build deterministic 5m bars whose values are a function of the UTC slot.

    Values depend only on the absolute slot number, so a pack that also contains
    earlier or later data repeats the same values at the same timestamps, and
    dropping a slot removes one bar without shifting any other bar's values.
    """
    dropped = set(int(item) for item in drop_slots)
    slots = np.array(
        [index for index in range(first_slot, first_slot + slot_count) if index not in dropped],
        dtype=np.int64,
    )
    stamps = anchor_ms + slots * STEP_MS
    position = slots.astype(np.float64)
    open_ = 100.0 + position
    values = np.column_stack(
        [open_, open_ + 2.0, open_ - 1.0, open_ + 1.0, 1000.0 + position]
    ).astype(dtype)
    return stamps, values


def instrument_source(
    timestamps: np.ndarray,
    ohlcv: np.ndarray,
    *,
    symbol: str = "AAA",
    venue: str = "TEST",
    contract: str = "AAA-USDT-SWAP",
    quote_currency: str = "USDT",
    roles: Sequence[str] = ("trading",),
    closed_before_ms: int | None = -1,
    volume_unit_evidence: str = "synthetic quote turnover generated by the test fixture",
    verification: Mapping[str, Any] | None = None,
) -> pack_data.InstrumentSource:
    """Build one publishable instrument; closure defaults to the coverage end.

    ``verification`` replaces the generated block, so a test can publish an
    explicitly malformed or unverified future state.
    """
    if closed_before_ms == -1:
        closed_before_ms = int(timestamps[-1]) + STEP_MS
    closure = None if closed_before_ms is None else utc(closed_before_ms)
    return pack_data.InstrumentSource(
        symbol=symbol,
        venue=venue,
        contract=contract,
        quote_currency=quote_currency,
        roles=list(roles),
        timestamps=timestamps,
        ohlcv=ohlcv,
        source=pack_manifest.build_source_metadata(
            input_format="synthetic",
            input_dtype=str(np.asarray(ohlcv).dtype),
            source_reference="tests/pattern_lab/_helpers.py synthetic generator",
            volume_unit_evidence=volume_unit_evidence,
        ),
        verification=verification
        if verification is not None
        else pack_manifest.build_verification(
            volume_quote_verified=True,
            volume_quote_evidence=volume_unit_evidence,
            closed_before_utc=closure,
            closure_evidence=None if closure is None else "synthetic fixture declares closed bars",
            closure_source=None if closure is None else "tests/pattern_lab/_helpers.py",
        ),
    )


def publish(
    root: Path,
    instruments: Sequence[pack_data.InstrumentSource],
    *,
    universe: Mapping[str, Any] | None = None,
    generated_utc: str = GENERATED_UTC,
    revision: int = 1,
) -> dict[str, Any]:
    """Publish a synthetic pack at ``root``."""
    return pack_data.publish_pack(
        root,
        list(instruments),
        universe=universe or pack_manifest.build_universe(notes="synthetic test fixture"),
        generated_utc=generated_utc,
        revision=revision,
    )


def single_pack(root: Path, *, slot_count: int = 288, **kwargs) -> tuple[np.ndarray, np.ndarray]:
    """Publish a one-instrument pack and return its canonical arrays."""
    stamps, values = synthetic_series(slot_count, drop_slots=kwargs.pop("drop_slots", ()))
    publish(root, [instrument_source(stamps, values, **kwargs)])
    return stamps, values


def read_raw_manifest(root: Path) -> dict[str, Any]:
    """Read the manifest as plain JSON, without Pattern Lab validation."""
    return json.loads((Path(root) / pack_manifest.MANIFEST_NAME).read_text(encoding="utf-8"))


def write_raw_manifest(root: Path, manifest: Mapping[str, Any]) -> None:
    """Write a manifest without validation, for negative and future-state fixtures."""
    (Path(root) / pack_manifest.MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )


def mutate_manifest(root: Path, mutate) -> dict[str, Any]:
    """Apply ``mutate`` to the raw manifest and write it back unvalidated."""
    manifest = read_raw_manifest(root)
    mutate(manifest)
    write_raw_manifest(root, manifest)
    return manifest


# --------------------------------------------------------------------------
# prototype NPZ pack builders, shared by the importer and CLI tests
# --------------------------------------------------------------------------

OKX_ID = "OKX_AAA-USDT-SWAP"
BYBIT_ID = "BYBIT_ENAUSDT"
OKX_ENDPOINT = "GET https://www.okx.com/api/v5/market/history-candles (bar=5m)"


def legacy_series(
    symbol: str = "AAA",
    venue: str = "OKX",
    contract: str = "AAA-USDT-SWAP",
    role: str = "trading",
    slot_count: int = 48,
    **extra: Any,
) -> dict[str, Any]:
    """Describe one prototype series; ``extra`` overrides any generated field."""
    stamps, values = synthetic_series(slot_count)
    spec = {
        "symbol": symbol,
        "venue": venue,
        "contract": contract,
        "role": role,
        "timestamps": stamps,
        "ohlcv": values.astype(np.float32),
        "scalars": True,
        "arrays": None,
    }
    spec.update(extra)
    return spec


def write_legacy_pack(root: Path, specs, *, manifest_overrides=None, entry_overrides=None) -> Path:
    """Write a prototype-layout NPZ pack at ``root`` and return it."""
    root = Path(root)
    (root / "5m").mkdir(parents=True)
    series = []
    for spec in specs:
        path = root / "5m" / f"{spec['symbol']}.npz"
        arrays = spec["arrays"]
        if arrays is None:
            arrays = {"ts": spec["timestamps"], "ohlcv": spec["ohlcv"]}
            if spec["scalars"]:
                arrays["ex"] = np.array(spec.get("scalar_venue", spec["venue"]))
                arrays["sym"] = np.array(spec.get("scalar_symbol", spec["symbol"]))
        np.savez_compressed(path, **arrays)
        entry = {
            "symbol": spec["symbol"],
            "venue": spec["venue"],
            "contract": spec["contract"],
            "role": spec["role"],
            "source_endpoint": OKX_ENDPOINT,
            "base_timeframe": "5m",
            "file": f"5m/{spec['symbol']}.npz",
            "bars": int(np.size(spec["timestamps"])),
            "first_ts_ms": int(np.min(spec["timestamps"])),
            "last_ts_ms": int(np.max(spec["timestamps"])),
            "sha256": pack_manifest.file_sha256(path),
        }
        entry.update(spec.get("entry_overrides") or {})
        entry.update(entry_overrides or {})
        series.append(entry)
    manifest = {
        "manifest_version": 1,
        "generated_utc": "2026-09-13T02:26:59Z",
        "volume_convention": "quote_volume_usd (USD notional), NOT base-asset volume.",
        "gap_policy": "Gaps < 3 bars are forward-filled with a stale flag.",
        "splits": {"discovery": [0.0, 0.65], "validation": [0.65, 0.85], "holdout": [0.85, 1.0],
                   "status": "discovery used; validation and holdout UNTOUCHED as of 2026-09-13"},
        "series": series,
    }
    manifest.update(manifest_overrides or {})
    (root / "MANIFEST.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8", newline="\n")
    return root


def sidecar(instruments=None, **overrides) -> dict[str, Any]:
    """Build a source-metadata sidecar; the default declares only the OKX series."""
    payload = {
        "schema_version": 1,
        "instruments": instruments
        if instruments is not None
        else {
            OKX_ID: {
                "quote_currency": "USDT",
                "volume_unit_evidence": "OKX swap volCcyQuote; fetch_base.py reads candle field 7.",
                "evidence_source": "Source review plus the OKX candle field definition",
            }
        },
    }
    payload.update(overrides)
    return payload


# --------------------------------------------------------------------------
# synthetic exchange protocol fixtures, shared by the collector tests
# --------------------------------------------------------------------------

EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)
OKX_CONTRACT = "AAA-USDT-SWAP"
BYBIT_CONTRACT = "BBBUSDT"
COLLECT_ROSTER_IDS = (f"BYBIT_{BYBIT_CONTRACT}", f"OKX_{OKX_CONTRACT}")


def roster_document(entries=None, **overrides):
    """Build a closed roster configuration document for the collector."""
    payload = {
        "schema_version": 1,
        "universe": {
            "selection_source": "tests/pattern_lab/_helpers.py synthetic roster",
            "selection_date": None,
            "historical_membership": "unknown",
            "notes": "synthetic test roster",
        },
        "instruments": entries
        if entries is not None
        else [
            {
                "instrument_id": f"BYBIT_{BYBIT_CONTRACT}",
                "symbol": "BBB",
                "venue": "BYBIT",
                "contract": BYBIT_CONTRACT,
                "quote_currency": "USDT",
                "roles": ["trading"],
            },
            {
                "instrument_id": f"OKX_{OKX_CONTRACT}",
                "symbol": "AAA",
                "venue": "OKX",
                "contract": OKX_CONTRACT,
                "quote_currency": "USDT",
                "roles": ["trading"],
            },
        ],
    }
    payload.update(overrides)
    return payload


def write_roster(path: Path, document=None) -> Path:
    """Write a roster configuration file and return its path."""
    path = Path(path)
    path.write_text(json.dumps(document or roster_document(), indent=2) + "\n", encoding="utf-8")
    return path


def okx_instrument(contract: str = OKX_CONTRACT, **overrides) -> dict[str, Any]:
    payload = {
        "instType": "SWAP",
        "instId": contract,
        "ctType": "linear",
        "settleCcy": "USDT",
        "ctVal": "0.1",
        "ctValCcy": contract.split("-")[0],
        "ctMult": "1",
        "lotSz": "1",
        "minSz": "1",
        "tickSz": "0.001",
        "listTime": "1700000000000",
        "state": "live",
    }
    payload.update(overrides)
    return payload


def bybit_instrument(contract: str = BYBIT_CONTRACT, **overrides) -> dict[str, Any]:
    lot = {"qtyStep": "0.1", "minOrderQty": "0.1", "minNotionalValue": "5", "maxOrderQty": "1000"}
    price = {"tickSize": "0.0001", "minPrice": "0.0001"}
    payload = {
        "symbol": contract,
        "contractType": "LinearPerpetual",
        "status": "Trading",
        "baseCoin": contract[:-4],
        "quoteCoin": "USDT",
        "settleCoin": "USDT",
        "launchTime": "1700000000000",
        "lotSizeFilter": dict(lot),
        "priceFilter": dict(price),
    }
    for key, value in overrides.items():
        if key in ("lotSizeFilter", "priceFilter") and isinstance(value, dict):
            payload[key] = {**payload[key], **value}
        else:
            payload[key] = value
    return payload


class FakeClock:
    """Deterministic monotonic clock, sleeper and wall clock."""

    def __init__(self, now_ms: int):
        self.now_ms = int(now_ms)
        self.elapsed = 0.0
        self.sleeps: list[float] = []

    def monotonic(self) -> float:
        return self.elapsed

    def sleep(self, seconds: float) -> None:
        self.sleeps.append(float(seconds))
        self.elapsed += float(seconds)

    def now_utc(self) -> datetime:
        return (EPOCH + timedelta(milliseconds=self.now_ms)).replace(microsecond=0)


class FakeExchange:
    """A synthetic OKX/Bybit protocol server over the injectable transport.

    The adapters' real request construction, cursor arithmetic and response
    decoding are exercised; only the socket is replaced. Series are stored as
    canonical 5m arrays, and a candle counts as closed once its close time is at
    or before the venue's current clock.
    """

    def __init__(self, *, now_ms: int):
        self.now_ms = int(now_ms)
        self.series: dict[tuple[str, str], tuple[np.ndarray, np.ndarray]] = {}
        self.instruments: dict[tuple[str, str], Any] = {}
        self.requests: list[tuple[str, dict[str, str]]] = []
        self.scripted: deque = deque()
        self.page_limit_override: int | None = None
        self.stall_after: int | None = None
        self.fail_time_for: set[str] = set()
        self._candle_calls = 0

    # -- fixture setup -----------------------------------------------------
    def add_okx(self, contract: str = OKX_CONTRACT, *, timestamps=None, ohlcv=None, metadata=None):
        self.series[("OKX", contract)] = (np.asarray(timestamps), np.asarray(ohlcv))
        self.instruments[("OKX", contract)] = (
            okx_instrument(contract) if metadata is None else metadata
        )

    def add_bybit(self, contract: str = BYBIT_CONTRACT, *, timestamps=None, ohlcv=None, metadata=None):
        self.series[("BYBIT", contract)] = (np.asarray(timestamps), np.asarray(ohlcv))
        self.instruments[("BYBIT", contract)] = (
            bybit_instrument(contract) if metadata is None else metadata
        )

    def set_rows(self, venue: str, contract: str, timestamps, ohlcv) -> None:
        self.series[(venue, contract)] = (np.asarray(timestamps), np.asarray(ohlcv))

    # -- transport ---------------------------------------------------------
    def __call__(self, url: str, timeout: float) -> exchange_data.HttpResponse:
        parsed = urllib.parse.urlparse(url)
        params = {key: value[0] for key, value in urllib.parse.parse_qs(parsed.query).items()}
        self.requests.append((parsed.path, params))
        if self.scripted:
            return self.scripted.popleft()
        handler = {
            "/api/v5/public/time": self._okx_time,
            "/api/v5/public/instruments": self._okx_instruments,
            "/api/v5/market/history-candles": self._okx_candles,
            "/v5/market/time": self._bybit_time,
            "/v5/market/instruments-info": self._bybit_instruments,
            "/v5/market/kline": self._bybit_candles,
        }.get(parsed.path)
        if handler is None:
            return exchange_data.HttpResponse(status=404, body="{}")
        return handler(params)

    def _json(self, payload) -> exchange_data.HttpResponse:
        return exchange_data.HttpResponse(status=200, body=json.dumps(payload))

    # -- OKX ---------------------------------------------------------------
    def _okx_time(self, params):
        if "OKX" in self.fail_time_for:
            return exchange_data.HttpResponse(status=500, body="{}")
        return self._json({"code": "0", "msg": "", "data": [{"ts": str(self.now_ms)}]})

    def _okx_instruments(self, params):
        key = ("OKX", params.get("instId", ""))
        if key not in self.instruments:
            return self._json({"code": "0", "msg": "", "data": []})
        return self._json({"code": "0", "msg": "", "data": [self.instruments[key]]})

    def _okx_candles(self, params):
        key = ("OKX", params.get("instId", ""))
        if key not in self.series:
            return self._json({"code": "51001", "msg": "Instrument ID does not exist", "data": []})
        stamps, values = self.series[key]
        after = int(params["after"])
        limit = self._limit(int(params["limit"]))
        chosen = np.flatnonzero(stamps < after)
        rows = []
        for index in chosen[::-1][:limit]:
            stamp = int(stamps[index])
            row = values[index]
            confirm = "1" if stamp + STEP_MS <= self.now_ms else "0"
            rows.append(
                [str(stamp), *(f"{float(item):.10f}" for item in row[:4]), "0", "0",
                 f"{float(row[4]):.10f}", confirm]
            )
        return self._json({"code": "0", "msg": "", "data": rows})

    # -- Bybit -------------------------------------------------------------
    def _bybit_time(self, params):
        if "BYBIT" in self.fail_time_for:
            return exchange_data.HttpResponse(status=500, body="{}")
        return self._json(
            {
                "retCode": 0,
                "retMsg": "OK",
                "result": {
                    "timeSecond": str(self.now_ms // 1000),
                    "timeNano": str(self.now_ms * 1_000_000),
                },
            }
        )

    def _bybit_instruments(self, params):
        key = ("BYBIT", params.get("symbol", ""))
        listing = [] if key not in self.instruments else [self.instruments[key]]
        return self._json(
            {"retCode": 0, "retMsg": "OK", "result": {"category": "linear", "list": listing}}
        )

    def _bybit_candles(self, params):
        symbol = params.get("symbol", "")
        key = ("BYBIT", symbol)
        if key not in self.series:
            return self._json({"retCode": 10001, "retMsg": "Not supported symbols", "result": {}})
        stamps, values = self.series[key]
        start, end = int(params["start"]), int(params["end"])
        limit = self._limit(int(params["limit"]))
        chosen = np.flatnonzero((stamps >= start) & (stamps <= end))
        rows = [
            [
                str(int(stamps[index])),
                *(f"{float(item):.10f}" for item in values[index][:4]),
                "0",
                f"{float(values[index][4]):.10f}",
            ]
            for index in chosen[::-1][:limit]
        ]
        return self._json(
            {
                "retCode": 0,
                "retMsg": "OK",
                "result": {"symbol": symbol, "category": "linear", "list": rows},
            }
        )

    def _limit(self, requested: int) -> int:
        self._candle_calls += 1
        if self.stall_after is not None and self._candle_calls > self.stall_after:
            return 0  # a repeated page with no progress
        if self.page_limit_override is not None:
            return min(requested, self.page_limit_override)
        return requested


def fake_client(exchange: FakeExchange, clock: FakeClock, **overrides) -> exchange_data.HttpClient:
    """Build the paced client used by the adapter-level tests."""
    options = {"timeout": 1.0, "max_attempts": 3, "rates": {"OKX": 1000.0, "BYBIT": 1000.0}}
    options.update(overrides)
    return exchange_data.HttpClient(transport=exchange, clock=clock, **options)


def collector_options(**overrides) -> dict[str, Any]:
    """Fast, deterministic pacing for the collector operation tests."""
    payload = {"okx_rps": 10.0, "bybit_rps": 10.0, "timeout_seconds": 1.0, "max_attempts": 3}
    payload.update(overrides)
    return payload
