"""Backtester V2 public contracts and reference runner."""

from .contracts import (
    EXECUTION_REASON_BOUNDARY_STATE,
    EXECUTION_REASON_MARGIN_REJECT,
    EXECUTION_REASON_MAX_DAYS_CLOSE_NEXT_OPEN,
    EXECUTION_REASON_NO_CAPITAL_HALT,
    EXECUTION_REASON_SIGNAL_ENTRY_NEXT_OPEN,
    EXECUTION_REASON_STOP_HIT,
    EXECUTION_REASON_TARGET_HIT,
    EXECUTION_REASON_TRAIL_RATCHET,
    GUARDRAIL_FLAG_CLAMP_MODE_USED,
    GUARDRAIL_FLAG_CORRECTED_FILL,
    GUARDRAIL_FLAG_INVALID_STOP_DISTANCE,
    GUARDRAIL_FLAG_LIQUIDATION,
    GUARDRAIL_FLAG_MARGIN_REJECT,
    GUARDRAIL_FLAG_NO_CAPITAL_HALT,
    GUARDRAIL_FLAG_REJECTED_FILL,
    GUARDRAIL_FLAG_ZERO_SIZE_ENTRY,
    ExecutionIntent,
    ExecutionProfile,
    GuardrailSummary,
    ModeBinding,
    OverlaySpec,
    Signals,
    StandingState,
    VariantSelector,
    VariantSpec,
)
from .kernel import ExecutionData, KernelConfig, KernelResult, intrabar_path, run_reference_kernel
from .runner import V2RunResult, build_kernel_config, run_v2_strategy

__all__ = [
    "EXECUTION_REASON_BOUNDARY_STATE",
    "EXECUTION_REASON_MARGIN_REJECT",
    "EXECUTION_REASON_MAX_DAYS_CLOSE_NEXT_OPEN",
    "EXECUTION_REASON_NO_CAPITAL_HALT",
    "EXECUTION_REASON_SIGNAL_ENTRY_NEXT_OPEN",
    "EXECUTION_REASON_STOP_HIT",
    "EXECUTION_REASON_TARGET_HIT",
    "EXECUTION_REASON_TRAIL_RATCHET",
    "GUARDRAIL_FLAG_CLAMP_MODE_USED",
    "GUARDRAIL_FLAG_CORRECTED_FILL",
    "GUARDRAIL_FLAG_INVALID_STOP_DISTANCE",
    "GUARDRAIL_FLAG_LIQUIDATION",
    "GUARDRAIL_FLAG_MARGIN_REJECT",
    "GUARDRAIL_FLAG_NO_CAPITAL_HALT",
    "GUARDRAIL_FLAG_REJECTED_FILL",
    "GUARDRAIL_FLAG_ZERO_SIZE_ENTRY",
    "ExecutionIntent",
    "ExecutionData",
    "ExecutionProfile",
    "GuardrailSummary",
    "KernelConfig",
    "KernelResult",
    "ModeBinding",
    "OverlaySpec",
    "Signals",
    "StandingState",
    "V2RunResult",
    "VariantSelector",
    "VariantSpec",
    "build_kernel_config",
    "intrabar_path",
    "run_reference_kernel",
    "run_v2_strategy",
]
